package com.archnet.ui.front;

import framework.components.HTMLTemplateContainer;

public class LoaderSkeletor extends HTMLTemplateContainer {

	public LoaderSkeletor(String name) {
		super(name, ""
				+ "        <header>\r\n"
				+ "            <div class=\"top-header d-none d-sm-block\">\r\n"
				+ "                <div class=\"container\">\r\n"
				+ "                    <div class=\"row\">\r\n"
				+ "                        <div class=\"col-lg-6\">\r\n"
				+ "                            <div class=\"header-contact\">\r\n"
				+ "                                <ul>\r\n"
				+ "                                    <li>Welcome to Our store Multikart</li>\r\n"
				+ "                                    <li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>Call Us: 123 - 456 - 7890</li>\r\n"
				+ "                                </ul>\r\n"
				+ "                            </div>\r\n"
				+ "                        </div>\r\n"
				+ "                        <div class=\"col-lg-6 text-end\">\r\n"
				+ "                            <ul class=\"header-dropdown\">\r\n"
				+ "                                <li class=\"mobile-wishlist\"><a href=\"#\"><i class=\"fa fa-heart\" aria-hidden=\"true\"></i></a>\r\n"
				+ "                                </li>\r\n"
				+ "                                <li class=\"onhover-dropdown mobile-account\">\r\n"
				+ "                                    <i class=\"fa fa-user\" aria-hidden=\"true\"></i> My Account\r\n"
				+ "                                </li>\r\n"
				+ "                            </ul>\r\n"
				+ "                        </div>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"container\">\r\n"
				+ "                <div class=\"row\">\r\n"
				+ "                    <div class=\"col-sm-12\">\r\n"
				+ "                        <div class=\"main-menu\">\r\n"
				+ "                            <div class=\"menu-left\">\r\n"
				+ "                                <div class=\"navbar\">\r\n"
				+ "                                    <a href=\"javascript:void(0)\">\r\n"
				+ "                                        <div class=\"bar-style\"><i class=\"fa fa-bars sidebar-bar\" aria-hidden=\"true\"></i>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </a>\r\n"
				+ "                                </div>\r\n"
				+ "                                <div class=\"brand-logo\">\r\n"
				+ "                                    <a href=\"index.html\"><img src=\"https://themes.pixelstrap.com/multikart/assets/images/icon/logo.png\" class=\"img-fluid blur-up lazyloaded\" alt=\"\"></a>\r\n"
				+ "                                </div>\r\n"
				+ "                            </div>\r\n"
				+ "                            <div class=\"menu-right pull-right\">\r\n"
				+ "                                <div>\r\n"
				+ "                                    <nav class=\"\">\r\n"
				+ "                                        <div class=\"toggle-nav\"><i class=\"fa fa-bars sidebar-bar\"></i></div>\r\n"
				+ "                                        <ul class=\"sm pixelstrap sm-horizontal hover-unset\">\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <div class=\"mobile-back text-end\">Back<i class=\"fa fa-angle-right ps-2\" aria-hidden=\"true\"></i></div>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <a href=\"index.html\">Home</a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <a href=\"#\">feature<div class=\"lable-nav\">new</div></a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <a href=\"#\">shop</a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <a href=\"#\">product</a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li>\r\n"
				+ "                                                <a href=\"#\">pages</a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li><a href=\"#\">blog</a>\r\n"
				+ "                                            </li>\r\n"
				+ "                                        </ul>\r\n"
				+ "                                    </nav>\r\n"
				+ "                                </div>\r\n"
				+ "                                <div>\r\n"
				+ "                                    <div class=\"icon-nav d-none d-sm-block\">\r\n"
				+ "                                        <ul>\r\n"
				+ "                                            <li class=\"onhover-div mobile-search\">\r\n"
				+ "                                                <div><img src=\"https://themes.pixelstrap.com/multikart/assets/images/icon/search.png\" onclick=\"openSearch()\" class=\"img-fluid blur-up lazyloaded\" alt=\"\"> <i class=\"ti-search\" onclick=\"openSearch()\"></i></div>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li class=\"onhover-div mobile-setting\">\r\n"
				+ "                                                <div><img src=\"https://themes.pixelstrap.com/multikart/assets/images/icon/setting.png\" class=\"img-fluid blur-up lazyloaded\" alt=\"\"> <i class=\"ti-settings\"></i></div>\r\n"
				+ "                                            </li>\r\n"
				+ "                                            <li class=\"onhover-div mobile-cart\">\r\n"
				+ "                                                <div><img src=\"https://themes.pixelstrap.com/multikart/assets/images/icon/cart.png\" class=\"img-fluid blur-up lazyloaded\" alt=\"\"> <i class=\"ti-shopping-cart\"></i></div>\r\n"
				+ "                                            </li>\r\n"
				+ "                                        </ul>\r\n"
				+ "                                    </div>\r\n"
				+ "                                </div>\r\n"
				+ "                            </div>\r\n"
				+ "                        </div>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "        </header>\r\n"
				+ "        <div class=\"breadcrumb-section\">\r\n"
				+ "            <div class=\"container\">\r\n"
				+ "                <div class=\"row\">\r\n"
				+ "                    <div class=\"col-sm-6\">\r\n"
				+ "                        <div class=\"page-title\">\r\n"
				+ "                            <h2>collection</h2>\r\n"
				+ "                        </div>\r\n"
				+ "                    </div>\r\n"
				+ "                    <div class=\"col-sm-6\">\r\n"
				+ "                        <nav aria-label=\"breadcrumb\" class=\"theme-breadcrumb\">\r\n"
				+ "                            <ol class=\"breadcrumb\">\r\n"
				+ "                                <li class=\"breadcrumb-item\"><a href=\"index.html\">home</a></li>\r\n"
				+ "                                <li class=\"breadcrumb-item active\" aria-current=\"page\">collection</li>\r\n"
				+ "                            </ol>\r\n"
				+ "                        </nav>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "        <section class=\"section-b-space ratio_asos\">\r\n"
				+ "            <div class=\"collection-wrapper\">\r\n"
				+ "                <div class=\"container\">\r\n"
				+ "                    <div class=\"row\">\r\n"
				+ "                        <div class=\"collection-content col\">\r\n"
				+ "                            <div class=\"page-main-content\">\r\n"
				+ "                                <div class=\"row\">\r\n"
				+ "                                    <div class=\"col-sm-12\">\r\n"
				+ "                                        <div class=\"top-banner-wrapper\">\r\n"
				+ "                                            <div class=\"img-ldr-top\"></div>\r\n"
				+ "                                            <div class=\"top-banner-content small-section\">\r\n"
				+ "                                                <h4></h4>\r\n"
				+ "                                                <h5></h5>\r\n"
				+ "                                                <p></p>\r\n"
				+ "                                                <p></p>\r\n"
				+ "                                            </div>\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <div class=\"collection-product-wrapper\">\r\n"
				+ "                                            <div class=\"product-top-filter\">\r\n"
				+ "                                                <div class=\"row m-0 w-100\">\r\n"
				+ "                                                    <div class=\"col-xl-4\">\r\n"
				+ "                                                        <div class=\"filter-panel\">\r\n"
				+ "                                                            <h6 class=\"ldr-text\"></h6>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-4 col-lg-4 col-6\">\r\n"
				+ "                                                        <div class=\"filter-panel\">\r\n"
				+ "                                                            <h6 class=\"ldr-text\"></h6>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-2 col-lg-4 col-6\">\r\n"
				+ "                                                        <div class=\"filter-panel\">\r\n"
				+ "                                                            <h6 class=\"ldr-text\"></h6>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-2 col-lg-4 d-none d-lg-block\">\r\n"
				+ "                                                        <div class=\"filter-panel\">\r\n"
				+ "                                                            <h6 class=\"ldr-text\"></h6>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                </div>\r\n"
				+ "                                            </div>\r\n"
				+ "                                            <div class=\"product-wrapper-grid\">\r\n"
				+ "                                                <div class=\"row\">\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                    <div class=\"col-xl-3 col-md-6 col-grid-box\">\r\n"
				+ "                                                        <div class=\"product-box\">\r\n"
				+ "                                                            <div class=\"img-wrapper\"></div>\r\n"
				+ "                                                            <div class=\"product-detail\">\r\n"
				+ "                                                                <h4></h4>\r\n"
				+ "                                                                <h5></h5>\r\n"
				+ "                                                                <h6></h6>\r\n"
				+ "                                                            </div>\r\n"
				+ "                                                        </div>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                </div>\r\n"
				+ "                                            </div>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </div>\r\n"
				+ "                                </div>\r\n"
				+ "                            </div>\r\n"
				+ "                        </div>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            </div>\r\n"
				+ "        </section>\r\n"
				+ "");
		
		 addClass("loader_skeleton");
	}

}
